baseURL = "https://cajustemohamedofficiel.github.io/mohamed-cajuste/"
languageCode = "en-us"
title = "Mohamed Cajuste"
theme = "PaperMod"

pagination.pagerSize = 10
enableRobotsTXT = true

[params]
  author = "Mohamed Cajuste"
  description = "Research-oriented portfolio"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  math = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 1

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4
